Repository metaplex-foundation/metaplex, pull requests merged in 2022-01, with the labels that each got.

#918 Add Slope wallet
  js/packages/cli/src/commands/upload.ts
  js/packages/cli/src/fair-launch-cli.ts
  js/packages/cli/src/helpers/gumdrop/communication.ts
  js/packages/cli/src/helpers/gumdrop/merkleTree.ts
  js/packages/common/package.json
  js/packages/common/src/contexts/wallet.tsx
  js/packages/gumdrop/src/utils/accounts.ts
  js/packages/gumdrop/src/utils/claimant.ts
  js/packages/gumdrop/src/utils/communication.ts
  js/packages/gumdrop/src/utils/ids.ts
  js/packages/gumdrop/src/utils/merkleDistributor.ts
  js/packages/gumdrop/src/utils/merkleTree.ts
  js/packages/gumdrop/src/utils/transactions.ts
  js/packages/web/package.json
  js/yarn.lock
Labels: enhancement

#1386 Deprecated candy machine v1 cli
  js/packages/cli/src/candy-machine-v1-cli.ts
  js/packages/cli/src/candy-machine-v2-cli.ts
  js/packages/cli/src/commands/upload.ts
  js/packages/cli/test/run-test-v1.sh
  js/packages/cli/test/run-test-v2.sh
Labels: Release V1.1.0

#1424 Deprecating Fair Launch Protocol UI
  .gitignore
  js/package.json
  js/packages/candy-machine-ui/.env.example
  js/packages/candy-machine-ui/package.json
  js/packages/candy-machine-ui/public/favicon.ico
  js/packages/candy-machine-ui/public/index.html
  js/packages/candy-machine-ui/public/logo192.png
  js/packages/candy-machine-ui/public/logo512.png
  js/packages/candy-machine-ui/public/manifest.json
  js/packages/candy-machine-ui/public/robots.txt
  js/packages/candy-machine-ui/src/App.css
  js/packages/candy-machine-ui/src/App.tsx
  js/packages/candy-machine-ui/src/Header.tsx
  js/packages/candy-machine-ui/src/Home.tsx
  js/packages/candy-machine-ui/src/MintButton.tsx
  js/packages/candy-machine-ui/src/MintCountdown.tsx
  js/packages/candy-machine-ui/src/candy-machine.ts
  js/packages/candy-machine-ui/src/connection.tsx
  js/packages/candy-machine-ui/src/index.css
  js/packages/candy-machine-ui/src/index.tsx
  js/packages/candy-machine-ui/src/logo.svg
  js/packages/candy-machine-ui/src/react-app-env.d.ts
  js/packages/candy-machine-ui/src/reportWebVitals.ts
  js/packages/candy-machine-ui/src/setupTests.ts
  js/packages/candy-machine-ui/src/utils.ts
  js/packages/candy-machine-ui/tsconfig.json
  js/packages/candy-machine-ui/yarn.lock
  js/packages/cli/src/fair-launch-cli.ts
  js/packages/fair-launch/.env
  js/packages/fair-launch/src/AntiRug.tsx
  js/packages/fair-launch/src/App.test.tsx
  js/packages/fair-launch/src/Home.tsx
  js/packages/fair-launch/src/PhaseHeader.tsx
  js/packages/fair-launch/src/confetti.tsx
  js/packages/fair-launch/src/fair-launch.ts
  js/yarn.lock
Labels: Fair Launch UI Deprecation

#1404 Improve error message
  js/packages/cli/src/commands/upload.ts
Labels: enhancement, Cli Tools

#1500 Make bundlr upload (arweave-sol) retry instead of ungraceful fail
  js/packages/cli/src/commands/upload.ts
  js/packages/cli/src/helpers/upload/arweave-bundle.ts
Labels: Community Dev

#1540 Fix serious verify command bug on rerun with partially verified cache
  js/packages/cli/src/candy-machine-v2-cli.ts
  js/packages/cli/src/commands/upload.ts
Labels: Community Dev

#1535 chore: fix README typo
  js/packages/cli/README.md
Labels: Community Dev

#1079 Add SMS to gumdrop and reduce claim transaction size
  js/packages/cli/src/gumdrop-cli.ts
  js/packages/cli/src/helpers/gumdrop/claimant.ts
  js/packages/cli/src/helpers/gumdrop/communication.ts
  js/packages/gumdrop/README.md
  js/packages/gumdrop/aws/index.js
  js/packages/gumdrop/package.json
  js/packages/gumdrop/src/App.tsx
  js/packages/gumdrop/src/components/Claim.tsx
  js/packages/gumdrop/src/components/Create.tsx
  js/packages/gumdrop/src/components/Header/Header.tsx
  js/packages/gumdrop/src/example.json
  js/packages/gumdrop/src/utils/claimant.ts
  js/packages/gumdrop/src/utils/communication.ts
Labels: Program: Gumdrop, Stale

#1076 chore: Enable lint for React components (TSX files)
  js/package.json
  js/packages/common/src/components/EtherscanLink/index.tsx
  js/packages/common/src/components/ExplorerLink/index.tsx
  js/packages/common/src/components/Settings/index.tsx
  js/packages/common/src/contexts/accounts/accounts.tsx
  js/packages/common/src/contexts/connection.tsx
  js/packages/common/src/contexts/meta/meta.tsx
  js/packages/common/src/contexts/wallet.tsx
  js/packages/web/src/actions/nft.tsx
  js/packages/web/src/components/AppBar/searchBox.tsx
  js/packages/web/src/components/ArtCard/index.tsx
  js/packages/web/src/components/ArtContent/index.tsx
  js/packages/web/src/components/ArtistAlleyForm/index.tsx
  js/packages/web/src/components/AuctionCard/index.tsx
  js/packages/web/src/components/AuctionNumbers/index.tsx
  js/packages/web/src/components/ClickToCopy/index.tsx
  js/packages/web/src/components/Confetti/index.tsx
  js/packages/web/src/components/CurrentUserBadge/index.tsx
  js/packages/web/src/components/Footer/index.tsx
  js/packages/web/src/components/InstructionsModal/index.tsx
  js/packages/web/src/components/Layout/index.tsx
  js/packages/web/src/components/MeshViewer/index.tsx
  js/packages/web/src/components/MetaAvatar/index.tsx
  js/packages/web/src/components/Notifications/index.tsx
  js/packages/web/src/components/SetupVariables/index.tsx
  js/packages/web/src/components/StaticPage/index.tsx
  js/packages/web/src/components/TokenDialog/index.tsx
  js/packages/web/src/components/UserSearch/index.tsx
  js/packages/web/src/contexts/coingecko.tsx
  js/packages/web/src/contexts/tokenList.tsx
  js/packages/web/src/pages/_app.tsx
  js/packages/web/src/pages/_document.tsx
  js/packages/web/src/pages/index.tsx
  js/packages/web/src/views/admin/index.tsx
  js/packages/web/src/views/analytics/index.tsx
  js/packages/web/src/views/artCreate/index.tsx
  js/packages/web/src/views/auction/billing.tsx
  js/packages/web/src/views/auction/index.tsx
  js/packages/web/src/views/auctionCreate/artSelector.tsx
  js/packages/web/src/views/auctionCreate/index.tsx
  js/packages/web/src/views/home/setup.tsx
  js/packages/web/src/views/preLaunch/index.tsx
Labels: Community
