Repository metaplex-foundation/metaplex, pull requests merged in 2022-02, with the labels that each got.

#1595 Allow regexp control characters in NFT name
  js/packages/cli/src/candy-machine-v2-cli.ts
Labels: invalid, discuss, priority: low

#1087 enhancement: Fetch prices in parallel
  js/packages/web/src/contexts/coingecko.tsx
Labels: enhancement, Store Front

#1601 Add mp4 (+ mov, mp3, flac, wav, glb, html) upload support in cm v2 cli
  js/packages/cli/src/candy-machine-v2-cli.ts
  js/packages/cli/src/commands/upload.ts
  js/packages/cli/src/commands/verifyTokenMetadata/index.ts
  js/packages/cli/src/commands/verifyTokenMetadata/token-metadata.schema.json
  js/packages/cli/src/helpers/constants.ts
  js/packages/cli/src/helpers/upload/arweave-bundle.ts
  js/packages/cli/src/helpers/upload/aws.ts
  js/packages/cli/src/helpers/upload/ipfs.ts
  js/packages/cli/src/helpers/upload/nft-storage.ts
Labels: enhancement, Cli Tools
